os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      0c62c65953239938e5534e41f9332603a38a37dc
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - cd app & npm install
  - cd app & npm install sqlite3 --build-from-source --runtime=node --target_arch=x64
  - cd app/app & npm install
  - npm install -g @angular/cli@6.0.8
  - cd app/app & ng build
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run build
artifacts:
  - path: dist\*.exe
    name: theapp
deploy:
  release: theapp-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    0c62c65953239938e5534e41f9332603a38a37dc
  artifact: /dist/.*\.exe/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only